site_name: Documentation Wiki

theme:
  name: material
  logo: assets/logo.svg
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
copyright: Copyright &copy; 2024 urban-cloud

nav:
  - Home: "index.md"

  
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
plugins:
  - search
